# هذا هو الجزء الأهم. يخبر Netlify بتوجيه أي طلب يأتي لموقعك
# (/*) إلى الدالة التي سننشئها
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/redirect"
  status = 200 # يعني "OK"، والدالة هي من سيقوم بالباقي