# netlify.toml

[build]
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/redirect"
  status = 200

# <<< أضف هذا القسم >>>
# هذا يخبر Netlify بتضمين الملف المحدد مع كل الدوال
[functions."*"]
  included_files = ["functions/server_url.txt"]
